---

- name: Systemd
  hosts: servers
  vars:
    systemd_services:
      - shadowsocks.service
      - acme-sh.service
      - acme-sh.timer

  tasks:
    - name: Check if service exists
      ansible.builtin.stat:
        path: '/usr/local/lib/systemd/system/{{ item }}'
      register: systemd_units
      loop: '{{ systemd_services }}'

    - name: Stop the services
      ansible.builtin.systemd_service:
        name: '{{ item.stat.path | basename }}'
        enabled: no
        state: stopped
      when: 'item.stat.exists'
      loop: '{{ systemd_units.results }}'

    - name: Remove unit files
      ansible.builtin.file:
        state: absent
        path: '/usr/local/lib/systemd/system/{{ item }}'
      loop: '{{ systemd_services }}'

- name: Configuration
  hosts: servers
  tasks:
    - name: Remove config files
      ansible.builtin.file:
        state: absent
        path: '/etc/shadowsocks/config.json'

- name: Acme certificates
  hosts: servers
  vars_files:
    - vars.yml

  tasks:
    - name: Remove generated certificates
      ansible.builtin.file:
        state: absent
        path: '{{ cert_dir }}'

- name: Executables
  hosts: servers
  vars:
    binaries:
      - acme.sh
      - ssserver
      - xray-plugin

  tasks:
    - name: Remove installed executables
      ansible.builtin.file:
        state: absent
        path: '/usr/local/bin/{{ item }}'
      loop: '{{ binaries }}'

- name: Users
  hosts: servers
  vars:
    entities:
      - acme.sh
      - shadowsocks

  tasks:
    - name: Remove created users
      ansible.builtin.user:
        name: '{{ item }}'
        state: absent
      loop: '{{ entities }}'

    - name: Remove created groups
      ansible.builtin.group:
        name: '{{ item }}'
        state: absent
      loop: '{{ entities }}'

- name: iptables
  hosts: servers
  tasks:
    - ansible.builtin.iptables:
        state: absent
        chain: INPUT
        protocol: tcp
        jump: REJECT
        reject_with: tcp-reset

    - ansible.builtin.iptables:
        state: absent
        chain: OUTPUT
        policy: ACCEPT

    - ansible.builtin.iptables:
        state: absent
        chain: '{{ item }}'
        policy: DROP
      with_items:
        - INPUT
        - FORWARD

    - ansible.builtin.iptables:
        state: absent
        chain: INPUT
        in_interface: eth0
        match: conntrack
        ctstate:
          - RELATED
          - ESTABLISHED
        jump: ACCEPT

    - ansible.builtin.iptables:
        state: absent
        chain: INPUT
        in_interface: eth0
        protocol: tcp
        match: multiport
        destination_port: "22,80,443"
        jump: ACCEPT

    - ansible.builtin.iptables:
        state: absent
        chain: INPUT
        in_interface: eth0
        protocol: icmp
        jump: ACCEPT

    - ansible.builtin.iptables:
        state: absent
        chain: INPUT
        match: conntrack
        ctstate:
          - INVALID
        jump: DROP

    - ansible.builtin.iptables:
        state: absent
        chain: INPUT
        in_interface: lo
        jump: ACCEPT
